Feature/portal_snap_functionality
virtual-disk-array/vda pull request #3
Opened 2021-09-07 11:41 UTC by huanzhang

2021-09-07 11:43 UTC, huanzhang reviewed
@yupeng0921 Hank, please have a look at this, I need more info about this feature. Thanks.

2021-09-07 14:35 UTC, yupeng0921 requested changes

2021-09-07 14:35 UTC, yupeng0921 commented on pkg/proto/portalapi/portalapi.proto
> +message CreateSnapRequest {
snap需要传入下列参数：
da_name (string)
snap_name (string)
description (string)
ori_name (string)
is_clone (bool)
size (uint64)

2021-09-07 14:35 UTC, yupeng0921 commented on pkg/portal/snap.go
> +		//另外，exp和snap什么区别，我忘记了:(
exp的解释见这里：
https://virtual-disk-array.readthedocs.io/en/latest/Introduction.html#exporter-exp
snap是下面文档中的snapshot或clone：
https://spdk.io/doc/logical_volumes.html

2021-09-07 14:35 UTC, yupeng0921 commented on pkg/portal/snap.go
> +		snap := &pbds.Snap{
除了CreateSnapRequest中的参数之外，还需id和idx。
id是一个uuid。
idx是一个顺序递增的数字，对于同一个da中的snap，后创建的idx必须要比以前创建的snap的idx更大。我原本打算是创建snap时，获取当前da的所有snap，找出最大的idx，然后加一。不过这样效率比较低，我突然想到，可以使用da的revision作为idx。etcd中的所有对象都有revision，在stm中可以通过Rev方法获取：
https://github.com/etcd-io/etcd/blob/main/client/v3/concurrency/stm.go#L32
可以就用这个revision作为idx。

2021-09-07 14:35 UTC, yupeng0921 commented on pkg/portal/snap.go
> +	for _, sockAddr := range cnSockAddrList {
snap只在primary上面出现，所以不需要syncup secondary。

2021-09-07 14:35 UTC, yupeng0921 commented on pkg/portal/snap.go
> +			if cntlr.IsPrimary {
除了获取primary的sockAddr之外，还需在primary上面创建SnapFrontend：
https://github.com/virtual-disk-array/vda/blob/master/pkg/proto/dataschema/dataschema.proto#L199
其中SnapFeConf的信息可以从Snap中获取，SnapFeInfo可以参考下面的Exp代码赋值：
https://github.com/virtual-disk-array/vda/blob/master/pkg/portal/exp.go#L88

2021-09-26 23:02 UTC, yupeng0921 requested changes

2021-09-26 23:02 UTC, yupeng0921 commented on pkg/portal/snap.go
> +			if cntlr.IsPrimary { // 如何在primary上面创建SnapFrontend, 通过调用jsonrpc创建另外的Snap么?还是只是创建对象？
只创建SnapFrontend对象就行，SyncupCn函数会将SnapFrontend传递给cn。创建SnapFrontend中有几点需要注意：
1. snap_id和SnapFeConf中的大部分信息都可以在Snap中找到，但OriId是例外。在Snap和CreateSnapRequest中使用的都是OriName。你需要遍历diskArray.SnapList，找到SnapName等于OriName的snap，把它的SnapId设置为OriId。
2. SnapFeInfo的设置可以参考ExpFeInfo：
https://github.com/virtual-disk-array/vda/blob/master/pkg/portal/exp.go#L88
3. 创建SnapFrontend之后，要将controllerNode.Version加一，表示这个controllerNode的配置更新了。之前我在创建exp时也忘记这点了，今天刚加上，参见：
https://github.com/virtual-disk-array/vda/blob/master/pkg/portal/exp.go#L138

2021-09-27 02:30 UTC, yupeng0921 commented
写完代码后，可以考虑如下方式进行测试：
创建一个snap，然后通过vda_admin命令确认etcd中的数据是否正确。vda的数据是以protobuf格式编码，存储在etcd中的。vda_admin的dump命令可以解码protubuf格式的数据，并转换为json格式，输出到一个文件。
例如，如果以minimal deployment文档中的参数部署vda服务：
https://virtual-disk-array.readthedocs.io/en/latest/MinimalDeployment.html
可以通过下面的命令分别将cn和da的数据保存到文件：
./vda_admin --etcd-endpoints localhost:2389 dump --keys /vda/cn/localhost:9820 --file-path /tmp/cn_data
 ./vda_admin --etcd-endpoints localhost:2389 dump --keys /vda/da/da0 --file-path /tmp/da_data
然后检查/tmp/cn_data中的snap_fe_list列表以及/tmp/da_data中的snap_list，确认写入到etcd中的数据是否正确。

2021-09-27 14:22 UTC, yupeng0921 requested changes

2021-10-18 14:55 UTC, yupeng0921 commented on pkg/portal/snap.go
> +			newSnapSize = uint64(diskArray.DaConf.StripSizeKb)
StripSizeKb不是卷的size，实际上da中并没有存储size，每个snap都有自己的size。所以req.Size为0时，要获取oriSnap.Size。另外，当用户设置了req.Size时，要判断一下req.Size和oriSnap.Size的大小，如果req.Size比oriSnap.Size小的话，应该返回错误，因为新的snap不能比之前的更小。

2021-10-21 03:58 UTC, yupeng0921 reviewed
这次看起来挺好的了，按照下面的方法测试一下，如果没问题的话，就可以合并了。
https://github.com/virtual-disk-array/vda/pull/3#issuecomment-927458952

2021-11-03 07:07 UTC, huanzhang commented
测试代码：
```
In [34]: request = portalapi.portalapi_pb2.CreateSnapRequest()

In [35]: stub.CreateSnap(request)
Out[35]:
reply_info {
  req_id: "a884dc11-ba5f-4142-805f-8255528dff2f"
  reply_code: 4
  reply_msg: "DaName is empty"
}


In [36]: request.da_name = "da0"

In [37]: request
Out[37]: da_name: "da0"

In [38]: stub.CreateSnap(request)
Out[38]:
reply_info {
  req_id: "19de67e6-50d2-4490-9b13-e7e1fa17b0e6"
  reply_code: 4
  reply_msg: "SnapName is empty"
}

In [39]: request.snap_name = "snap0"

In [40]: stub.CreateSnap(request)
Out[40]:
reply_info {
  req_id: "96339f60-f554-42be-871c-c5063836c699"
  reply_msg: "succeed"
}
```

测试结果：
测试前da
```
[
  {
    "Key": "/vda/da/da0",
    "Revision": 16,
    "Value": {
      "da_id": "5a4121edf95b4c1f8b32122b7eb7c056",
      "da_name": "da0",
      "da_conf": {
        "qos": {},
        "strip_cnt": 1,
        "strip_size_kb": 64
      },
      "cntlr_list": [
        {
          "cntlr_id": "aadbea69edab4282b4b786b2f1c40932",
          "cn_sock_addr": "localhost:9820",
          "is_primary": true,
          "cn_nvmf_listener": {
            "tr_type": "tcp",
            "adr_fam": "ipv4",
            "tr_addr": "127.0.0.1",
            "tr_svc_id": "4430"
          }
        }
      ],
      "grp_list": [
        {
          "grp_id": "354eb56c75da45ae97c7b29fd756d599",
          "size": 67108864,
          "vd_list": [
            {
              "vd_id": "4b81968824324751a6b59be877a65f6c",
              "size": 67108864,
              "dn_sock_addr": "localhost:9720",
              "pd_name": "pd0",
              "qos": {}
            }
          ]
        }
      ],
      "snap_list": [
        {
          "snap_id": "8eddfb99db904a37929758e0c97f0e92",
          "snap_name": "%default%",
          "description": "default snap",
          "size": 67108864
        }
      ]
    }
  }
]
```
测试前cn
```
[
  {
    "Key": "/vda/cn/localhost:9820",
    "Revision": 568,
    "Value": {
      "cn_id": "fe75e6d36dce4f88bfd99fb8b156ad7e",
      "sock_addr": "localhost:9820",
      "version": 2,
      "cn_conf": {
        "nvmf_listener": {
          "tr_type": "tcp",
          "adr_fam": "ipv4",
          "tr_addr": "127.0.0.1",
          "tr_svc_id": "4430"
        },
        "hash_code": 4723
      },
      "cn_info": {
        "err_info": {
          "timestamp": "2021-11-03 03:31:26.557355211 +0000 UTC"
        }
      },
      "cn_capacity": {
        "cntlr_cnt": 1
      },
      "cntlr_fe_list": [
        {
          "cntlr_id": "aadbea69edab4282b4b786b2f1c40932",
          "cntlr_fe_conf": {
            "da_id": "5a4121edf95b4c1f8b32122b7eb7c056",
            "da_name": "da0",
            "strip_size_kb": 64,
            "cntlr_list": [
              {
                "cntlr_id": "aadbea69edab4282b4b786b2f1c40932",
                "cn_sock_addr": "localhost:9820",
                "is_primary": true,
                "cn_nvmf_listener": {
                  "tr_type": "tcp",
                  "adr_fam": "ipv4",
                  "tr_addr": "127.0.0.1",
                  "tr_svc_id": "4430"
                }
              }
            ]
          },
          "cntlr_fe_info": {
            "err_info": {
              "is_err": true,
              "err_msg": "GrpFeError",
              "timestamp": "2021-11-03 03:31:26.502974515 +0000 UTC"
            }
          },
          "grp_fe_list": [
            {
              "grp_id": "354eb56c75da45ae97c7b29fd756d599",
              "grp_fe_conf": {
                "size": 67108864
              },
              "grp_fe_info": {
                "err_info": {
                  "is_err": true,
                  "err_msg": "VdFeError",
                  "timestamp": "2021-11-03 03:31:26.502968042 +0000 UTC"
                }
              },
              "vd_fe_list": [
                {
                  "vd_id": "4b81968824324751a6b59be877a65f6c",
                  "vd_fe_conf": {
                    "dn_nvmf_listener": {
                      "tr_type": "tcp",
                      "adr_fam": "ipv4",
                      "tr_addr": "127.0.0.1",
                      "tr_svc_id": "4420"
                    },
                    "dn_sock_addr": "localhost:9720",
                    "size": 67108864
                  },
                  "vd_fe_info": {
                    "err_info": {
                      "is_err": true,
                      "err_msg": "bdev_nvme_attach_controller rsp err: -32602 Invalid parameters",
                      "timestamp": "2021-11-03 03:31:26.50295722 +0000 UTC"
                    }
                  }
                }
              ]
            }
          ],
          "snap_fe_list": [
            {
              "snap_id": "8eddfb99db904a37929758e0c97f0e92",
              "snap_fe_conf": {
                "size": 67108864
              },
              "snap_fe_info": {
                "err_info": {
                  "is_err": true,
                  "err_msg": "no info",
                  "timestamp": "2021-11-03 03:31:26.55773322 +0000 UTC"
                }
              }
            }
          ]
        }
      ]
    }
  }
]
```
测试后da
```
[vagrant@fedora33 project]$ ./cat_da_data.sh
2021/11/03 06:57:14.415284 I | stm apply, DumpKey 1
2021/11/03 06:57:14.419699 I | Done
[
  {
    "Key": "/vda/da/da0",
    "Revision": 2970,
    "Value": {
      "da_id": "5a4121edf95b4c1f8b32122b7eb7c056",
      "da_name": "da0",
      "da_conf": {
        "qos": {},
        "strip_cnt": 1,
        "strip_size_kb": 64
      },
      "cntlr_list": [
        {
          "cntlr_id": "aadbea69edab4282b4b786b2f1c40932",
          "cn_sock_addr": "localhost:9820",
          "is_primary": true,
          "cn_nvmf_listener": {
            "tr_type": "tcp",
            "adr_fam": "ipv4",
            "tr_addr": "127.0.0.1",
            "tr_svc_id": "4430"
          }
        }
      ],
      "grp_list": [
        {
          "grp_id": "354eb56c75da45ae97c7b29fd756d599",
          "size": 67108864,
          "vd_list": [
            {
              "vd_id": "4b81968824324751a6b59be877a65f6c",
              "size": 67108864,
              "dn_sock_addr": "localhost:9720",
              "pd_name": "pd0",
              "qos": {}
            }
          ]
        }
      ],
      "snap_list": [
        {
          "snap_id": "8eddfb99db904a37929758e0c97f0e92",
          "snap_name": "%default%",
          "description": "default snap",
          "size": 67108864
        },
        {
          "snap_id": "1992548653734152aab4e1bfec4ac70d",
          "snap_name": "snap0",
          "ori_name": "%default%",
          "idx": 16,
          "size": 67108864
        }
      ]
    }
  }
]
```
测试后cn
```
[vagrant@fedora33 project]$ ./cat_cn_data.sh
2021/11/03 06:57:46.016911 I | stm apply, DumpKey 1
2021/11/03 06:57:46.024339 I | Done
[
  {
    "Key": "/vda/cn/localhost:9820",
    "Revision": 3044,
    "Value": {
      "cn_id": "fe75e6d36dce4f88bfd99fb8b156ad7e",
      "sock_addr": "localhost:9820",
      "version": 3,
      "cn_conf": {
        "nvmf_listener": {
          "tr_type": "tcp",
          "adr_fam": "ipv4",
          "tr_addr": "127.0.0.1",
          "tr_svc_id": "4430"
        },
        "hash_code": 4723
      },
      "cn_info": {
        "err_info": {
          "timestamp": "2021-11-03 06:57:41.564447207 +0000 UTC"
        }
      },
      "cn_capacity": {
        "cntlr_cnt": 1
      },
      "cntlr_fe_list": [
        {
          "cntlr_id": "aadbea69edab4282b4b786b2f1c40932",
          "cntlr_fe_conf": {
            "da_id": "5a4121edf95b4c1f8b32122b7eb7c056",
            "da_name": "da0",
            "strip_size_kb": 64,
            "cntlr_list": [
              {
                "cntlr_id": "aadbea69edab4282b4b786b2f1c40932",
                "cn_sock_addr": "localhost:9820",
                "is_primary": true,
                "cn_nvmf_listener": {
                  "tr_type": "tcp",
                  "adr_fam": "ipv4",
                  "tr_ad [...]

2021-11-03 07:11 UTC, huanzhang commented
OriName参数测试：
```
In [41]: request.snap_name = "snap1"

In [42]: request.ori_name = "snapxxx"

In [43]: stub.CreateSnap(request)
Out[43]:
reply_info {
  req_id: "fff42b89-78a1-4856-a3bd-68002ba87d15"
  reply_code: 1
  reply_msg: "request parameter err: Snap is not existed with given OriName"
}

In [44]: request.ori_name = "snap0"

In [45]: stub.CreateSnap(request)
Out[45]:
reply_info {
  req_id: "e835cc50-3f5a-4f9a-af15-5d5fbe8c7a81"
  reply_msg: "succeed"
}
```
测试后da
```
[vagrant@fedora33 project]$ ./cat_da_data.sh
2021/11/03 07:10:56.126719 I | stm apply, DumpKey 1
2021/11/03 07:10:56.130733 I | Done
[
  {
    "Key": "/vda/da/da0",
    "Revision": 3195,
    "Value": {
      "da_id": "5a4121edf95b4c1f8b32122b7eb7c056",
      "da_name": "da0",
      "da_conf": {
        "qos": {},
        "strip_cnt": 1,
        "strip_size_kb": 64
      },
      "cntlr_list": [
        {
          "cntlr_id": "aadbea69edab4282b4b786b2f1c40932",
          "cn_sock_addr": "localhost:9820",
          "is_primary": true,
          "cn_nvmf_listener": {
            "tr_type": "tcp",
            "adr_fam": "ipv4",
            "tr_addr": "127.0.0.1",
            "tr_svc_id": "4430"
          }
        }
      ],
      "grp_list": [
        {
          "grp_id": "354eb56c75da45ae97c7b29fd756d599",
          "size": 67108864,
          "vd_list": [
            {
              "vd_id": "4b81968824324751a6b59be877a65f6c",
              "size": 67108864,
              "dn_sock_addr": "localhost:9720",
              "pd_name": "pd0",
              "qos": {}
            }
          ]
        }
      ],
      "snap_list": [
        {
          "snap_id": "8eddfb99db904a37929758e0c97f0e92",
          "snap_name": "%default%",
          "description": "default snap",
          "size": 67108864
        },
        {
          "snap_id": "1992548653734152aab4e1bfec4ac70d",
          "snap_name": "snap0",
          "ori_name": "%default%",
          "idx": 16,
          "size": 67108864
        },
        {
          "snap_id": "ea0768aa42b745eb80527506486314a3",
          "snap_name": "snap1",
          "ori_name": "snap0",
          "idx": 2970,
          "size": 67108864
        }
      ]
    }
  }
]
```
@yupeng0921 Please review, thanks!

2021-11-05 15:46 UTC, yupeng0921 approved these changes

2021-11-05 15:47 UTC, merged